Support aws provider 4.x
lacework/terraform-aws-config pull request #39
Opened 2022-03-03 21:28 UTC by naseemkullah

## Summary

Support 4.x of aws provider, see https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md

## How did you test this change?

vendored this module into our repo and adjusted the provider restraint for aws

## Issue

2022-03-03 23:25 UTC, afiune requested changes

2022-03-03 23:25 UTC, afiune commented on versions.tf
> +    aws    = ">= 3.35"
Could we add a more restricted constraint, we don't know if `5.0` will have breaking changes that will affect this module, what we have done in other modules is https://github.com/lacework/terraform-gcp-config/blob/main/versions.tf#L5
```suggestion
    aws    = ">= 3.35.0, < 5.0.0"
```

2022-03-04 17:42 UTC, naseemkullah commented
Constraint updated as per your suggestion @afiune

2022-03-10 18:33 UTC, afiune approved these changes
![tenor-42629871](https://user-images.githubusercontent.com/5712253/157731365-b8e32996-32a4-48c1-8fc2-8f0f8f5ab7ba.gif)

2022-03-10 18:33 UTC, merged

2022-03-11 01:00 UTC, naseemkullah commented
thanks! any plan to cut a release soon?